/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package edu.austral.dissis.chess

import edu.austral.dissis.chess.common.Game
import edu.austral.dissis.chess.chess.boarderReader.BoarderReader
import edu.austral.dissis.chess.chess.createValidationEngine.ClassicEngine
import edu.austral.dissis.chess.common.ChessPiece
import edu.austral.dissis.chess.common.victoryValidators.CheckmateValidator
import edu.austral.dissis.chess.common.victoryValidators.NoOppPiecesValidator
import edu.austral.dissis.chess.gui.*
import javafx.application.Application
import javafx.application.Application.launch
import javafx.scene.Scene
import javafx.stage.Stage


fun main() {
    launch(ChessGameApplication::class.java)
}

class ChessGameApplication : Application() {
    private val chessPieces = listOf(ChessPiece.BISHOP, ChessPiece.HORSE, ChessPiece.KING, ChessPiece.PAWN, ChessPiece.QUEEN, ChessPiece.ROOK)
    private val boarderReader = BoarderReader(chessPieces, ClassicEngine())
//    private val checkmatePieces = boarderReader.boarderReader("/home/constanza/projects/facu/system_design/chess-app/app/src/main/kotlin/edu/austral/dissis/chess/checkmate.txt", ClassicEngine(), chessPieces)
//    private val noMoreOpponentPieces = boarderReader.boarderReader("/home/constanza/projects/facu/system_design/chess-app/app/src/main/kotlin/edu/austral/dissis/chess/NoMoreOppPieces", ClassicEngine(), chessPieces)
    private val pieces = boarderReader.getMap("/home/constanza/projects/facu/system_design/chess-app/app/src/main/kotlin/edu/austral/dissis/chess/beginning")
    private val adapter = Game(pieces, PlayerColor.BLACK, 8, listOf(CheckmateValidator(), NoOppPiecesValidator()))
    private val imageResolver = CachedImageResolver(DefaultImageResolver())

    companion object {
        const val GameTitle = "Chess"
    }

    override fun start(primaryStage: Stage) {
        primaryStage.title = GameTitle

        val root = GameView(adapter, imageResolver)
        primaryStage.scene = Scene(root)

        primaryStage.show()
        println(ChessPiece.KING.toString()[0])
    }
}